version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo "Entering project directory"
      - cd cicdapp
      - echo "Java version:"
      - java -version
      - echo "Maven version:"
      - mvn -v

  build:
    commands:
      - mvn -B clean test package

  post_build:
    commands:
      - echo "Build completed"
      - ls -la target
      - cp target/*.war target/ROOT.war

artifacts:
  base-directory: cicdapp/target
  files:
    - ROOT.war
  discard-paths: yes
